import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@uploadthing/react/styles.css";
import { SessionProvider } from "@/components/providers/SessionProvider";
import { UploadThingProvider } from "@/components/providers/UploadThingProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-zinc-100 selection:bg-red-500`}
        style={{ backgroundColor: '#171717' }}
      >
        
        <SessionProvider>
          <UploadThingProvider>
            {children}
          </UploadThingProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
